version: '3.9'

services:
  app:
    build: .
    container_name: oluwaseyiolubiyi/my-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5431/signIn_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: postgres:latest
    container_name: POSTGRES
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: signIn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data/var/lib/postgresql/data

volumes:
  postgres_data:
